global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'usuarios-servicio'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['usuarios-servicio:8080']

  - job_name: 'asignaturas-servicio'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['asignaturas-servicio:8082']

  - job_name: 'matriculas-servicio'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['matriculas-servicio:8083']
